"""Application-wide constants not suitable for YAML (identifiers only)."""

HEALTH_OK = "healthy"
HEALTH_DEGRADED = "degraded"

ERROR_CONFIG_INVALID = "configuration_invalid"
ERROR_UPLOAD_EMPTY = "upload_empty"
ERROR_UPLOAD_UNSUPPORTED = "upload_unsupported"
ERROR_QUERY_EMPTY = "query_empty"
ERROR_LLM_UNAVAILABLE = "llm_unavailable"
ERROR_WEBSITE_INGEST_EMPTY = "website_ingest_empty"
ERROR_CRAWL_START_FAILED = "crawl_start_failed"
ERROR_RATE_LIMIT = "rate_limit_exceeded"
ERROR_JIRA_CONFIG = "jira_not_configured"
ERROR_JIRA_API = "jira_api_error"
ERROR_TICKET_CREATE = "ticket_create_failed"
ERROR_TICKET_ATTACHMENT = "ticket_attachment_not_found"
